import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/db/mongoose';
import Post from '@/lib/db/models/Post';
import { requireAdmin } from '@/lib/auth/requireAdmin';

/**
 * GET /api/posts
 * Fetch posts with pagination and filtering
 */
export async function GET(request: NextRequest) {
  try {
    await connectDB();

    const searchParams = request.nextUrl.searchParams;
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '10');
    const category = searchParams.get('category');
    const status = searchParams.get('status') || 'published';
    const sort = searchParams.get('sort') || 'publishedAt';

    // Build query
    const query: any = { status: 'published' };

    // For admin requests, allow different status filters
    const { authenticated } = await requireAdmin();
    if (authenticated && status) {
      query.status = status;
    }

    if (category) {
      query.category = category;
    }

    // Calculate pagination
    const skip = (page - 1) * limit;

    // Build sort object
    const sortObj: any = {};
    if (sort === 'createdAt') {
      sortObj.createdAt = -1;
    } else {
      sortObj.publishedAt = -1;
    }

    // Fetch posts with selected fields only
    const posts = await Post.find(query)
      .select('title slug excerpt featuredImage category categoryLabel publishedAt readTime featured trending editorsPick status views createdAt')
      .sort(sortObj)
      .skip(skip)
      .limit(limit)
      .lean();

    // Get total count for pagination
    const total = await Post.countDocuments(query);
    const totalPages = Math.ceil(total / limit);

    return NextResponse.json({
      posts,
      total,
      page,
      totalPages,
    });
  } catch (error) {
    console.error('Error fetching posts:', error);
    return NextResponse.json(
      { error: 'Failed to fetch posts' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/posts
 * Create a new post (admin only)
 */
export async function POST(request: NextRequest) {
  try {
    // Check authentication
    const { authenticated } = await requireAdmin();
    if (!authenticated) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    await connectDB();

    const body = await request.json();

    // Validate required fields
    const { title, excerpt, content, category } = body;
    if (!title || !excerpt || !content || !category) {
      return NextResponse.json(
        { error: 'Missing required fields: title, excerpt, content, category' },
        { status: 400 }
      );
    }

    // Create new post
    const post = new Post({
      ...body,
      // Slug will be auto-generated by pre-save hook if not provided
    });

    await post.save();

    return NextResponse.json(
      { post, message: 'Post created successfully' },
      { status: 201 }
    );
  } catch (error: any) {
    console.error('Error creating post:', error);
    
    // Handle duplicate slug error
    if (error.code === 11000) {
      return NextResponse.json(
        { error: 'Post with this slug already exists' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: 'Failed to create post' },
      { status: 500 }
    );
  }
}
